language: node_js
os: linux
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
script:
  - npm run docs:build
deploy:
  provider: pages
  cleanup: false
  local_dir: .vuepress/dist/
  token: $GH_TOKEN # Set in travis-ci.org dashboard
  fqdn: docs.vechain.org
  on:
    branch: master