language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
script:
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: .vuepress/dist/
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  fqdn: docs.vechain.org
  on:
    branch: master